// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdnbpbbwlcxfbiakegnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbmJwYmJ3bGN4ZmJpYWtlZ25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDA3ODIsImV4cCI6MjA2Nzk3Njc4Mn0.tzjFdV0FieoaDqybeyoFtl_yOMibQhYUv7m7x-jr1mY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});